name: CI Pipeline

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download JSON schema
        run: |
          curl -OJ https://www.hl7.org/fhir/fhir.schema.json.zip
          unzip -uoq fhir.schema.json
          rm fhir.schema.json.zip
          mv fhir.schema.json schema.json
      - name: Apply JSON patch
        run: |
          pip install --user jsonpatch
          jsonpatch --in-place schema.json patch.json
      - name: Push changes
        run: |
          if [[ -n $(git status -s) ]]
          then
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git config --global user.name "${GITHUB_ACTOR}"
            git add schema.json
            git commit -m "Update JSON schemas"
            git push
          fi
